name = "InfrastructureModels"
uuid = "2030c09a-7f63-5d83-885d-db604e0e9cc0"
authors = ["Carleton Coffrin"]
repo = "https://github.com/lanl-ansi/InfrastructureModels.jl"
version = "0.3.2"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"

[compat]
JuMP = "~0.19.1, ~0.20.0"
Memento = "~0.10, ~0.11, ~0.12"
julia = "^1"

[extras]
ECOS = "e2685f51-7e38-5353-a97d-a921fd2c8199"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ECOS", "Ipopt", "Juniper", "JSON", "MathOptInterface", "Random", "Test"]
