name = "InfrastructureModels"
uuid = "e8e45514-c753-11e8-2a1b-cd93cb9d98d1"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"

[extras]
ECOS = "e2685f51-7e38-5353-a97d-a921fd2c8199"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Ipopt", "ECOS", "JSON", "Juniper"]
